### ISSUE TITLE
Permashift fails to compile with vdr 2.1.7

### ISSUE THREAD

**Issue by hertell** [eikesauer/Permashift#1]
When i patched vdr 2.1.7 vdr fails to compile with this error:

g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -c -DUSE_WAREAGLEICON -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DREMOTE_KBD -DLIRC_DEVICE=\"/var/run/lirc/lircd\" -DVIDEODIR=\"/data/recordings/video0\" -DCONFDIR=\"/data/home/vdr_ubuntu/config\" -DARGSDIR=\"/etc/vdr/conf.d\" -DCACHEDIR=\"/data/recordings/video0\" -DRESDIR=\"/data/recordings/video0\" -DPLUGINDIR=\"/data/home/vdr_ubuntu/vdr-2.1.7/PLUGINS/lib\" -DLOCDIR=\"/data/home/vdr_ubuntu/vdr-2.1.7/locale\" -I/usr/include/freetype2    -o recorder.o recorder.c
recorder.c: In constructor ‘cRecorder::cRecorder(const char_, const cChannel_, int)’:
recorder.c:31:35: error: ‘InitializeFile’ was not declared in this scope
recorder.c: At global scope:
recorder.c:35:77: error: no ‘void cRecorder::InitializeFile(const char_, const cChannel_)’ member function declared in class ‘cRecorder’
make: **\* [recorder.o] Error 1

also recorder.h fails to patch with the following error:

--- recorder.h  2014-09-11 18:55:49.485113436 +0200
+++ recorder.h  2014-03-20 19:53:17.293197434 +0100
@@ -33,16 +33,11 @@
   virtual void Activate(bool On);
   virtual void Receive(uchar *Data, int Length);
   virtual void Action(void);
-  void InitializeFile(const char *FileName, const cChannel *Channel);
-               ///< Starts recording to file.
## \-               ///< Called in constructor if file name has been given.

 public:
   cRecorder(const char *FileName, const cChannel *Channel, int Priority);
-               ///< Creates a new recorder for the given Channel and
-               ///< the given Priority that will record into the file FileName.
-               // Creates a new recorder for the given Channel and
- ```
            // the given Priority that will record into the file FileName.
  ```
  ## virtual ~cRecorder();
  
  };
  # endif //__RECORDER_H

**Comment by eikesauer** [comment]
Thanks for your report! 
Could you plase try if this patch works for you?
https://gist.github.com/eikesauer/1efcaf6cd318aa31765d
(I used the new version 2.1.8 as base.)

**Comment by hertell** [comment]
Sorry for not replying earlier! :-(

This patch worked perfectly now on vdr 2.1.8

Thanks!

**Comment by hertell** [comment]
Hi!
The patch does not work anymore with vdr 2.1.9 :-( I'll check later tonight if i can manually add it.

**Comment by eikesauer** [comment]
_gna_
Here we go...
https://gist.github.com/eikesauer/0e9e9a63de8739defce8

**Comment by hertell** [comment]
Hi!
This went throug! You should maybe add it to the Git-repo, because the original patch does not work anymore :-)

**Comment by eikesauer** [comment]
I've put the patch where it belongs. Hope it will work on 2.2.0... ;)
